version: "3"
services:
  jacm-back:
    container_name: jacm-back
    command: npm start
    network_mode: host
    build: .
    volumes:
      - ./:/usr/src/backend
    env_file:
      - .env
    ports:
      - "3000:3000"
